### ISSUE TITLE
Solr_wrapper command fails

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/SearchWorks#3109]
```
solr_wrapper
Starting Solr 8.11.1 on port 8983 ... /Users/jcoyne85/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/solr_wrapper-4.0.2/lib/solr_wrapper/instance.rb:324:in `exec': Failed to execute solr create:  (RuntimeError)
ERROR: Error CREATEing SolrCore 'blacklight-core': Unable to create core [blacklight-core] Caused by: edu.stanford.lucene.analysis.ICUCustomTransformCharFilterFactory

. Further information may be available in /var/folders/2d/4qv8jcd52mjbybw4zyt0mkmm0000gs/T/solr-8.11.1/server/logs
	from /Users/jcoyne85/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/solr_wrapper-4.0.2/lib/solr_wrapper/instance.rb:161:in `create'
	from /Users/jcoyne85/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/solr_wrapper-4.0.2/lib/solr_wrapper/instance.rb:218:in `with_collection'
	from /Users/jcoyne85/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/solr_wrapper-4.0.2/exe/solr_wrapper:114:in `block in <top (required)>'
	from /Users/jcoyne85/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/solr_wrapper-4.0.2/lib/solr_wrapper/instance.rb:65:in `wrap'
	from /Users/jcoyne85/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/solr_wrapper-4.0.2/exe/solr_wrapper:113:in `<top (required)>'
	from /Users/jcoyne85/.rbenv/versions/3.2.1/bin/solr_wrapper:25:in `load'
	from /Users/jcoyne85/.rbenv/versions/3.2.1/bin/solr_wrapper:25:in `<main>'
```

**Comment by jcoyne** [comment]
Needed to `rake searchworks:install` first.
